### ISSUE TITLE
Propose Anthelion for Nutch Trunk

### ISSUE THREAD

**Issue by lewismc** [yahoo/anthelion#1]
Hi Folks,
Are you interested in proposing Anthelion for integration into the Nutch trunk source code?
I think I've spoken with a few of you over on the Any23 ML and I am very glad to see you publish the outcome of the work as source code.
What do you guys think? I am one of the main developers of Nutch and Any23 so I am very interested in seeing this plugin available for more to use.

**Comment by lewismc** [comment]
@RobertMeusel @petarR

**Comment by RobertMeusel** [comment]
Hi Lewis, 

Yes we are interested in including the plugin within the Apache Nutch trunk. I discussed with Petar - who was doing the major work of the integration - and before integration we see some potential for improvements where you might be the right person to help. How should we proceed?

Robert

**Comment by lewismc** [comment]
> How should we proceed?

Well your work has made it to the [Nutch lists](http://www.mail-archive.com/user%40nutch.apache.org/msg14094.html) already :)

I suggest that we try to factor out your plugin and rebase on trunk (should be a piece of cake) Also can you log an issue in the [Nutch issue tracker](https://issues.apache.org/jira/browse/NUTCH) ?

Would be excellent to get the contribution in to trunk @RobertMeusel

**Comment by Kseniyayoung** [comment]
WAY   = Apps     нет лишнего слишком активный Yahoo  но это пока любознательность просто а так мне нравиться и pic moven

**Comment by RobertMeusel** [comment]
Issues is in the tracker @lewismc

**Comment by lewismc** [comment]
Thanks @RobertMeusel lets track it over there from now on. For reference the issue is logged at https://issues.apache.org/jira/browse/NUTCH-2202
